# Dependencies
gems: [jekyll-paginate]

# Permalinks
#
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Anmol Bhullar
tagline:             'An Undergraduate Attempts Math'
description:         'My personal website where I have my resume and showcase some of my side projects'
url:                 http://anmolbhullar.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anmol Bhullar
  url:               https://twitter.com/mdo
  email:             anmol.bhullar@mail.utoronto.ca

# Custom vars
version:             1.0.0
